@startuml UseCase

left to right direction

'Attori'
actor Sistema
actor "Utente" as Utente <<abstract>>
actor "Utente Autenticato" as Utente_Autenticato
actor "Utente Non Autenticato" as Utente_Non_Autenticato

rectangle UniTeam {
    'Use Case Sistema'
    usecase Autenticazione
    usecase "Crea Account" as Crea_Account
    usecase "Invia Email di\\nVerifica" as Invia_Email_Verifica 
    usecase "Recupero Password" as Recupero_Password
    usecase "Gestione Gruppi" as Gestione_Gruppi
    usecase "Gestione Recensioni" as Gestione_Recensioni
   

    'Use Case Utente'
    usecase "Legge Recensione" as Legge_Recensione
    usecase "Ricerca Gruppo" as Ricerca_Gruppo
    usecase "Visualizza informazioni Corso" as Visualizza_Info_Corso
    usecase "Visualizza informazioni Professore" as Visualizza_Info_Professore

    'Use Case Utente Non Autenticato'
    usecase Accesso
    usecase Registrazione
    usecase "Verifica Email" as Verifica_Email

    'Use Case Utente Autenticato'
    usecase "Modifica Profilo" as Modifica_Profilo
    usecase "Crea Gruppo" as Crea_Gruppo
    usecase "Accesso a un Gruppo" as Accesso_Gruppo 
    usecase "Elimina Gruppo" as Elimina_Gruppo
    usecase "Gestione Gruppo" as Gestione_Gruppo
    usecase "Scrive Recensione" as Scrive_Recensione
    usecase "Scrive Recensione\\nCorso" as Scrive_Recensione_Corso
    usecase "Scrive Recensione\\nProfessore" as Scrive_Recensione_Professore
    usecase "Modifica Recensione" as Modifica_Recensione
    usecase "Modifica Recensione\\nCorso" as Modifica_Recensione_Corso
    usecase "Modifica Recensione\\nProfessore" as Modifica_Recensione_Professore
}

'Utente'
Utente <|-- Utente_Autenticato
Utente <|-- Utente_Non_Autenticato

'Registrazione'
Sistema -- Crea_Account
Crea_Account ..> Invia_Email_Verifica : <<include>>
Crea_Account ..> Verifica_Email: <<include>>

Utente_Non_Autenticato -- Registrazione
Registrazione <.. Crea_Account : <<extend>>
note on link
    Condizione: 
    Email disponibile
    Formato credenziali corretto

    Extension point: 
    Crea Account
end note

Utente_Non_Autenticato -- Verifica_Email

'Accesso'
Utente_Non_Autenticato -- Accesso
Accesso <.. Autenticazione : <<extend>>
note on link
    Condizione: 
    Credenziali corrette

    Extension point: 
    Autenticazione
end note

Accesso <.. Recupero_Password : <<extend>>
Sistema -- Autenticazione

'Profilo'
Utente_Autenticato -- Modifica_Profilo

'Recensioni'
Scrive_Recensione <|-- Scrive_Recensione_Corso
Scrive_Recensione <|-- Scrive_Recensione_Professore
Modifica_Recensione <|-- Modifica_Recensione_Corso
Modifica_Recensione <|-- Modifica_Recensione_Professore

Utente -- Legge_Recensione
Utente_Autenticato -- Scrive_Recensione
Utente_Autenticato -- Modifica_Recensione

Sistema -- Gestione_Recensioni
Gestione_Recensioni -- Scrive_Recensione
Gestione_Recensioni -- Modifica_Recensione

'Gruppi'
Gestione_Gruppo <|-- Crea_Gruppo
Gestione_Gruppo <|-- Elimina_Gruppo

Sistema -- Gestione_Gruppi
Utente_Autenticato -- Gestione_Gruppo
Utente_Autenticato -- Accesso_Gruppo
Utente -- Ricerca_Gruppo

Gestione_Gruppi -- Gestione_Gruppo


'Corsi'
Utente -- Visualizza_Info_Corso


'Professori'
Utente -- Visualizza_Info_Professore

@enduml

'https://stackoverflow.com/questions/48712801/how-to-correct-plantuml-line-path'