@startuml

|Utente| 
|Sistema|
|Supabase Service|




|Utente| 
start
:Utente clicca sul tasto d'accesso;

|Sistema|
:Mostra Pagina Accesso;

|Utente|
:Inserisce Credenziali;

|Sistema|
:Tentativo di Accesso;

|Supabase Service|
:Richesta Accesso con credenziali;

if (Account esistente) then (No) 
  |Sistema|
  :Mostra messaggio di errato inserimento;
  
  |Utente|
  :Preme il pulsante:\n'Non hai ancora un account? Registrati';

  |Sistema|
  :Mostra Pagina Registrazione;

  repeat
  repeat
  |Utente|
  :Inserisce credenziali;
  
  |Sistema|
  :Controllo Credenziali;
  repeat while (Credenziali Valide?) is (No)
  ->Si;
  
  |Utente|
  :Preme Pulsante 'Registrati';
  
  |Sistema|
  :Tentativo di Registrazione;

  |Supabase Service|
  :Richesta Registrazione con email e password;
  
  |Sistema|
  backward :Mostra messaggio errore;
  repeat while (Email è gia in uso?) is (Si)
  ->No;

  |Supabase Service|
  fork
  :Invia email di verifica\nall'indirizzo fornito;
  
  fork again
  :Aggiunge account con stato di 'waiting';
  
  end fork 

'TODO
  'Per quanto riguarda la verifica della mail bisogna trovare
  'se esiste un blocco che rappresenta un 'evento temporale, 
  'altrimenti direi di collegare direttamente il blocco in parallelo 
  'con "Apre link di verifica". 
  
  |Utente|
  :Apre link di verifica;
  
  |Supabase Service|
  repeat
  backward :Controlla Stato;
  repeat while (Email verificata?) is (No)

else(Si)
  |Sistema|
  :Reindirizza alla pagina precedente;
  stop
endif

->Si;
fork
|Sistema|
:Aggiornamento dati sessione utente;

fork again
|Supabase Service|
:Account Verificato\nRimuove Stato 'waiting';

|Supabase Service|
|Sistema|
end fork

:Reindirizza alla pagina precedente;
stop
@enduml