@startuml
!define AuthGuard
!define TextBox
!define ArrowNew
!define ReviewBox
!define Diamond
!define Process
!define Start

||

if (Utente Autenticato?) then (Sì)
  :L'utente è autenticato;
else (No)
  :L'utente non è autenticato;
  :Effettua Accesso;
  if (Accesso Riuscito?) then (Sì)
    
  else (No)
    :Accesso Fallito;
    :Annulla Recensione;
    stop
  endif
endif

:Scrivi Recensione;
    if (Recensione Completa?) then (Sì)
        :Conferma Recensione;
        if (Recensione Approvata?) then (Sì)
        :Recensione Pubblicata;
        stop
        else (No)
        :Recensione Non Approvata;
        stop
        endif
    else (No)
        :Recensione Incompleta;
        :Annulla Recensione;
        stop
    endif
@enduml