@startuml ActivityDiagram

|Utente| 
|Sistema|
|Supabase Service|
|Database|

|Utente| 
start
:Utente clicca sul tasto d'accesso;

|Sistema|
:Mostra Pagina Accesso;

|Utente|
:Inserisce Credenziali;

|Sistema|
:Tentativo di Accesso;

|Supabase Service|
:Richesta Accesso con credenziali;

if (Account esistente) then (No) 
  |Sistema|
  :Mostra messaggio di errato inserimento;
  
  |Utente|
  :Preme il pulsante:\n'Non hai ancora un account? Registrati';

  |Sistema|
  :Mostra Pagina Registrazione;

  repeat
  repeat
  |Utente|
  :Inserisce credenziali;
  
  |Sistema|
  :Controllo Credenziali;
  repeat while (Credenziali Valide?) is (No)
  ->Si;
  
  |Utente|
  :Preme Pulsante 'Registrati';
  
  |Sistema|
  :Richesta di Registrazione;

  |Supabase Service|
  :Registrazione con email e password;
  
  backward :Mostra messaggio errore;
  
  repeat while (Email è gia in uso?) is (Si)
  ->No;

  |Supabase Service|
  fork
  :Invia email di verifica\nall'indirizzo fornito;
  
  fork again
  |Database|
  :Aggiunge account con stato di 'waiting';
  |Supabase Service|
  end fork 
  
  |Utente|
  :Apre link di verifica;
  
  |Sistema|
  :Richiesta di verifica;

  |Supabase Service|
  if (Richiesta Valida) then (Sì)
    
  else (No)
    |Sistema|
    :Mostra messaggio di errore;
    stop
  endif
  

else(Si)
  |Sistema|
  :Reindirizza alla pagina precedente;
  stop
endif

|Supabase Service|
fork
:Aggiornamento dati sessione utente;

fork again
:Account Verificato;
|Database|
:Rimuove Stato 'waiting';

|Supabase Service|
end fork


|Sistema|
:Reindirizza alla pagina precedente;
stop
@enduml