@startuml
|Utente| --> (Inizia)
fork
    :Esecuzione parallela 1;
    :Esecuzione parallela 2;
fork again
    :Esecuzione parallela 3;
    :Esecuzione parallela 4;
end fork
|Utente| --> (Fine)

|Utente| --> (Inizia)
|Utente| --> (Fine)
|Utente| --> (Errore)

note left of (Inizia)
    Questo è lo stato iniziale del processo.
end note

note right of (Fine)
    Questo è lo stato finale del processo.
end note

note right of (Errore)
    Questo stato rappresenta un errore nel processo.
end note



@enduml
