@startuml Sitemap

skinparam linetype ortho

rectangle HomePage

rectangle Account
together {
rectangle Il_mio_profilo as "Il mio profilo"
rectangle Le_mie_recensioni as "Le mie recensioni"
rectangle I_miei_gruppi as "I miei gruppi"
rectangle Ripristino_password_account as "Ripristino Password"
}

rectangle Login
rectangle Registrazione
rectangle Gruppi
rectangle Corsi
rectangle Professori




rectangle Ripristino_password_profilo as "Ripristino Password"

rectangle Gruppo
rectangle Corso
rectangle Professore

HomePage -- Account
Account -[hidden]- HomePage

Account -- Il_mio_profilo
Account -- Le_mie_recensioni
Account -- I_miei_gruppi

Il_mio_profilo -- Ripristino_password_profilo

HomePage -- Login
Login -- Ripristino_password_account

HomePage -- Registrazione



HomePage -- Gruppi
Gruppi -- Gruppo

HomePage -- Corsi
Corsi -- Corso

HomePage -- Professori
Professori -- Professore



@enduml
